services:

  web:
    image: php:8.2-apache
    container_name: borrowing-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: borrowing-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sports_borrow_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: borrowing-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db